### ISSUE TITLE
Failing to instal Geneland

### ISSUE THREAD

**Issue by lenkaungrova** [gilles-guillot/Geneland#2]
Hi,

I have successfully installed Geneland multiple times on my mac, but now I am failing to install it correctly and I do not know why. I think I have some issues with gfortran
Is there any information about what version of R I need for this version of Geneland and which version of gfortran?
I am able to install it somehow and also run MCMC, but then PostProcessChain is not working and whole R session is terminaned.

I am running it on MacOS Big Sur and I was able to install it successfully before, but not now.

Thank you for your help.

**Comment by gilles-guillot** [comment]
Hi, 
the Fortran compiler required by R to compile packages and the one distributed with MacOS were compatible for years but this does not seem to be the case anymore for more than a year.  Working myself only under Linux, I am unable to provide any help on this issue and can only recommend to use Geneland under Linux or Windows if this is possible for you.

**Comment by lenkaungrova** [comment]
Thank you for your quick answer!

I tried to install it on Windows, with the newest R and RTools version, but it has the same output. Installation without any error, everything seems fine during the analysis (used the GUI). But again, session aborted when I try to PostProcessChain command after MCMC analysis. 

Do you have any idea what to do? Thanks.

**Comment by gilles-guillot** [comment]
Then I would not call this an installation issue, but rather an execution issue.
Can you please report exact command triggering the problem and the error message you receive?

**Comment by lenkaungrova** [comment]
First, I run this command in R studio
MCMC(coordinates = geneland_coord,geno, .dip.codom = geneland_geno, path.mcmc = "./", npopmin = 1, npopmax = 3, nit = 100000, thinning = 100, freq.model = "Correlated",spatial = TRUE) 
setting just to test if it is working

I also can do this in the GUI interface.

then this warning message occur when using just R studio (no warning when using GUI):
Warning message:
In MCMC(coordinates = geneland_coord, geno.dip.codom = geneland_geno,  :
  passing a char vector to .Fortran is not portable

second, I want to run this command:

PostProcessChain(coordinates = geneland_coord, path.mcmc = "./", nxdom = 50, nydom = 50, burnin = 100)

 When I run this using GUI, R studio crushes without any error warning. When I use commands just in R studio, it allows me to proceed the data. 
 
 I am not sure, if the software is running correctly when receiving this warning message.

**Comment by gilles-guillot** [comment]
"When I run this using GUI, R studio crushes without any error warning. When I use commands just in R studio, it allows me to proceed the data."
Can you pls clarify this?

**Comment by lenkaungrova** [comment]
When I run this PostProcessChain command using GUI, a pop up window "R Session Aborted: R encountered a fatal error. The session was terminated" and R Studio and Geneland GUI both terminated. No error written.
When I do this using just commands in R Studio this PostProcessChain command is  finished, but also with this warnings (14 and all the same): 
_"Warning messages:
1: In PostProcessChain(coordinates = geneland_coord, path.mcmc = "./",  ... :
  passing a char vector to .Fortran is not portable"_

I can generate plots etc after that. But I do not know what the warning
 _"In MCMC(coordinates = geneland_coord, geno.dip.codom = geneland_geno, :passing a char vector to .Fortran is not portable"_ 
means and how it affects the outputs of Geneland and also why the GUI is not working anymore. 

I tried to install it on another computer, also Windows and also used the newest releases of R, R Studio and RTools. Same problem. 

I am sorry I am so bad at explaining things. :) Thanks for helping

**Comment by gilles-guillot** [comment]
So using Geneland under Rstudio, there is no particular problem?

**Comment by lenkaungrova** [comment]
The two warnings appeared but that is all. Do you know what they mean?

**Comment by gilles-guillot** [comment]
The title of this thread is misleading. There is no installation issue.
